"use client";

import React, { useState } from "react";
import { Download, FileJson, FileText, Printer, Copy, Check } from "lucide-react";
import { toast } from "sonner";
import { cn } from "@/lib/utils";

interface ExportMenuProps {
  title: string;
  data: Record<string, unknown> | object;
  markdownContent?: string;
  className?: string;
}

export function ExportMenu({
  title,
  data,
  markdownContent,
  className,
}: ExportMenuProps) {
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  const downloadJson = () => {
    const jsonStr = JSON.stringify(data, null, 2);
    const blob = new Blob([jsonStr], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${title.toLowerCase().replace(/\s+/g, "_")}_export.json`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Exported JSON report");
    setOpen(false);
  };

  const copyMarkdown = () => {
    const content =
      markdownContent ||
      `# ${title}\n\nGenerated by Pedago AI Evidence Copilot\n\n\`\`\`json\n${JSON.stringify(
        data,
        null,
        2
      )}\n\`\`\``;

    navigator.clipboard.writeText(content);
    setCopied(true);
    toast.success("Copied Markdown report to clipboard");
    setTimeout(() => setCopied(false), 2000);
    setOpen(false);
  };

  const handlePrint = () => {
    setOpen(false);
    window.print();
  };

  return (
    <div className={cn("relative inline-block", className)}>
      <button
        onClick={() => setOpen(!open)}
        className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-border bg-background text-xs font-medium text-foreground hover:bg-muted transition-colors shadow-xs"
      >
        <Download className="h-3.5 w-3.5" />
        <span>Export</span>
      </button>

      {open && (
        <div
          className="absolute right-0 mt-1.5 w-52 rounded-xl border border-border bg-popover p-1 shadow-lg z-50 animate-in fade-in zoom-in-95 duration-100"
          onMouseLeave={() => setOpen(false)}
        >
          <button
            onClick={copyMarkdown}
            className="flex w-full items-center gap-2 px-3 py-2 text-xs rounded-lg hover:bg-muted text-foreground text-left transition-colors"
          >
            {copied ? <Check className="h-3.5 w-3.5 text-emerald-500" /> : <Copy className="h-3.5 w-3.5" />}
            <span>Copy as Markdown</span>
          </button>

          <button
            onClick={downloadJson}
            className="flex w-full items-center gap-2 px-3 py-2 text-xs rounded-lg hover:bg-muted text-foreground text-left transition-colors"
          >
            <FileJson className="h-3.5 w-3.5" />
            <span>Download JSON Audit</span>
          </button>

          <button
            onClick={handlePrint}
            className="flex w-full items-center gap-2 px-3 py-2 text-xs rounded-lg hover:bg-muted text-foreground text-left transition-colors"
          >
            <Printer className="h-3.5 w-3.5" />
            <span>Print / Save as PDF</span>
          </button>
        </div>
      )}
    </div>
  );
}
